// Market layer figures, generated by bettor-segmentation/src/export_market_figures.py.
// The league tables come from that repo's SQL run unchanged, on Pinnacle closing
// prices. The open versus close work uses the average-price layer, because
// opening prices are only widely populated for the average.

import raw from "@/data/market-figures.json";

export interface LeagueEfficiencyRow {
  tier: string;
  league_name: string;
  matches: number;
  overround_pct: number;
  brier: number;
  brier_ci95: number;
}

export interface CalibrationNoiseRow {
  tier: string;
  league_name: string;
  outcomes: number;
  observed_pp: number;
  noise_pp: number;
  ratio: number;
}

export interface CalibrationBin {
  lo: number;
  hi: number;
  n: number;
  predicted: number;
  actual: number;
}

export interface MovementBand {
  lo_pp: number;
  hi_pp: number;
  matches: number;
  gain: number;
  ci95: number;
}

export interface MarketHeadline {
  matches: number;
  brier_open: number;
  brier_close: number;
  gain: number;
  gain_ci95: [number, number];
  t_stat: number;
  move_median_pp: number;
  move_p90_pp: number;
  favourite_flipped: number;
}

export interface MarketFigures {
  league_efficiency: LeagueEfficiencyRow[];
  calibration_vs_noise: CalibrationNoiseRow[];
  calibration: { open: CalibrationBin[]; close: CalibrationBin[] };
  movement_bands: MovementBand[];
  headline: MarketHeadline;
}

export const marketFigures: MarketFigures = raw as unknown as MarketFigures;
